version: '3'

services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_DB=mydb
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypass
    ports:
      - "5432:5432"
    volumes:
      - my-db:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin@example.com
      - PGADMIN_DEFAULT_PASSWORD=secret
    ports:
      - "5050:80"
volumes:
  my-db:


